=== ssyablonskaya/new-utility-hierarchy/src/main/resources/hierarchyschema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="organization">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="address">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="city" type="xs:string" use="optional"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="director">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="headName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="employees">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employee" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstName" type="xs:string"/>
                                        <xs:element name="lastName" type="xs:string"/>
                                        <xs:element name="dob" type="xs:dateTime"/>
                                        <xs:element name="position" type="xs:string"/>
                                        <xs:element name="salary">
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="services">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="service" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="serviceName"/>
                                        <xs:element name="price">
                                        </xs:element>
                                        <xs:element name="doTime">
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="type" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="materials">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="material" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="materialName" type="xs:string"/>
                                        <xs:element name="materialPrice">
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="type" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ssyablonskaya/new-utility-hierarchy/src/main/resources/hierarchy.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<organization xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hierarchyschema.xsd">
    <name>utility-service</name>
    <address city="Minsk">Vaneeva, 32</address>
    <director>
        <firstName>Mr</firstName>
        <lastName>Director</lastName>
    </director>
    <employees>
        <employee>
            <firstName>Alex</firstName>
            <lastName>Frost</lastName>
            <dob>2001-11-03T00:00:00</dob>
            <position>accountant</position>
            <salary currency="rub">1700</salary>
        </employee>
        <employee>
            <firstName>John</firstName>
            <lastName>Snow</lastName>
            <dob>1994-10-02T00:00:00</dob>
            <position>plumber</position>
            <salary currency="rub">1300</salary>
        </employee>
    </employees>
    <services>
        <service type="plumbing">
            <name>installation of meters</name>
            <price currency="rub">22</price>
            <doTime unit="hours">2</doTime>
        </service>
        <service type="repairing">
            <name>fixing inside walls</name>
            <price currency="rub">22</price>
            <doTime unit="hours">8</doTime>
        </service>
    </services>
    <materials>
        <material type="repairing">
            <name>paint</name>
            <price currency="rub">7</price>
        </material>
        <material type="plumbing">
            <name>water tap</name>
            <price currency="rub">32</price>
        </material>
    </materials>
</organization>
